#python ../CombineTools/scripts/plotLimits.py 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_nobbb_lumi50_ggH_cmb.json'  'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH_cmb.json:exp0:MarkerSize=0.5,Title="Alt median"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH_cmb.json:exp-1:MarkerSize=0.5,LineStyle=2,Title="Alt -1 sigma"'  'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH_cmb.json:exp+1:MarkerSize=0.5,LineStyle=2,Title="Alt +1 sigma"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH_cmb.json:exp-2:MarkerSize=0.5,LineStyle=7,Title="Alt -2 sigma"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH_cmb.json:exp+2:MarkerSize=0.5,LineStyle=7,Title="Alt +2 sigma"'  --logy --auto-style --y-title "Limit on gg#Phi" --output="ECFA_noshapes_normalrebin_lumi50_bbbcompare_ggH" --ratio-to="mssm_projection_ECFA_noshapes_normalrebin_shiftcen_nobbb_lumi50_ggH_cmb.json:exp0" --show exp
#python ../CombineTools/scripts/plotLimits.py 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_nobbb_lumi1_ggH_cmb.json'  'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH_cmb.json:exp0:MarkerSize=0.5,Title="Alt median"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH_cmb.json:exp-1:MarkerSize=0.5,LineStyle=2,Title="Alt -1 sigma"'  'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH_cmb.json:exp+1:MarkerSize=0.5,LineStyle=2,Title="Alt +1 sigma"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH_cmb.json:exp-2:MarkerSize=0.5,LineStyle=7,Title="Alt -2 sigma"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH_cmb.json:exp+2:MarkerSize=0.5,LineStyle=7,Title="Alt +2 sigma"'  --logy --auto-style --y-title "Limit on gg#Phi" --output="ECFA_noshapes_normalrebin_lumi1_bbbcompare_ggH" --ratio-to="mssm_projection_ECFA_noshapes_normalrebin_shiftcen_nobbb_lumi1_ggH_cmb.json:exp0" --show exp
#python ../CombineTools/scripts/plotLimits.py 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_nobbb_lumi100_ggH_cmb.json'  'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH_cmb.json:exp0:MarkerSize=0.5,Title="Alt median"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH_cmb.json:exp-1:MarkerSize=0.5,LineStyle=2,Title="Alt -1 sigma"'  'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH_cmb.json:exp+1:MarkerSize=0.5,LineStyle=2,Title="Alt +1 sigma"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH_cmb.json:exp-2:MarkerSize=0.5,LineStyle=7,Title="Alt -2 sigma"' 'mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH_cmb.json:exp+2:MarkerSize=0.5,LineStyle=7,Title="Alt +2 sigma"'  --logy --auto-style --y-title "Limit on gg#Phi" --output="ECFA_noshapes_normalrebin_lumi100_bbbcompare_ggH" --ratio-to="mssm_projection_ECFA_noshapes_normalrebin_shiftcen_nobbb_lumi100_ggH_cmb.json:exp0" --show exp

python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_normalrebin_shiftcen_lumi1_ggH_cmb.json,mssm_projection_ECFA_shapes_normalrebin_shiftcen_nobbb_lumi1_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_normalrebin_lumi1_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}" --custom_y_range --y_axis_max=1.5 --y_axis_min=0.5
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_normalrebin_shiftcen_lumi50_ggH_cmb.json,mssm_projection_ECFA_shapes_normalrebin_shiftcen_nobbb_lumi50_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_normalrebin_lumi50_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->50 fb^{-1}" --custom_y_range --y_axis_max=2 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_normalrebin_shiftcen_lumi100_ggH_cmb.json,mssm_projection_ECFA_shapes_normalrebin_shiftcen_nobbb_lumi100_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_normalrebin_lumi100_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->100 fb^{-1}" --custom_y_range --y_axis_max=3 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_normalrebin_shiftcen_lumi300_ggH_cmb.json,mssm_projection_ECFA_shapes_normalrebin_shiftcen_nobbb_lumi300_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_normalrebin_lumi300_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->300 fb^{-1}" --custom_y_range --y_axis_max=3 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p8_shiftcen_nobbb_lumi1_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p8_lumi1_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}" --custom_y_range --y_axis_max=1.5 --y_axis_min=0.5
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p8_shiftcen_nobbb_lumi50_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p8_lumi50_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->50 fb^{-1}" --custom_y_range --y_axis_max=2 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p8_shiftcen_nobbb_lumi100_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p8_lumi100_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->100 fb^{-1}" --custom_y_range --y_axis_max=3 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p8_shiftcen_nobbb_lumi300_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p8_lumi300_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->300 fb^{-1}" --custom_y_range --y_axis_max=3 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p5_shiftcen_lumi1_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p5_shiftcen_nobbb_lumi1_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p5_lumi1_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}" --custom_y_range --y_axis_max=1.5 --y_axis_min=0.5
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p5_shiftcen_lumi50_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p5_shiftcen_nobbb_lumi50_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p5_lumi50_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->50 fb^{-1}" --custom_y_range --y_axis_max=2 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p5_shiftcen_lumi100_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p5_shiftcen_nobbb_lumi100_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p5_lumi100_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->100 fb^{-1}" --custom_y_range --y_axis_max=3 --y_axis_min=0
python scripts/MSSMlimitCompare.py --file=mssm_projection_ECFA_shapes_rebin0p5_shiftcen_lumi300_ggH_cmb.json,mssm_projection_ECFA_shapes_rebin0p5_shiftcen_nobbb_lumi300_ggH_cmb.json  --labels="bbb,no bbb" --plot_sigmas --outname="ECFA_shapes_rebin0p5_lumi300_bbbcompare_ggH" --process="gg#phi" --channel_label=" " --title="2.3 fb^{-1}->300 fb^{-1}" --custom_y_range --y_axis_max=3 --y_axis_min=0
