combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.lumi1.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.lumi10.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi10_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.lumi50.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.lumi100.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.lumi300.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi300_ggH.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.lumi1.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.lumi10.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi10_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.lumi50.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.lumi100.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.lumi300.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi300_bbH.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.S0.lumi1.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_ggH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.S0.lumi10.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi10_ggH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.S0.lumi50.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_ggH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.S0.lumi100.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_ggH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.ggH.S0.lumi300.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi300_ggH_S0.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.S0.lumi1.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi1_bbH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.S0.lumi10.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi10_bbH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.S0.lumi50.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi50_bbH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.S0.lumi100.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi100_bbH_S0.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_noshapes_normalrebin_shiftcen/cmb/higgsCombine.bbH.S0.lumi300.* --use-dirs -o "mssm_projection_ECFA_noshapes_normalrebin_shiftcen_lumi300_bbH_S0.json"
