#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_ggH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_ggH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_ggH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_ggH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_ggH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_ggH.json"

#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_bbH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_bbH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_bbH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_bbH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_bbH.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_bbH.json"

#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.S0.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_ggH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.S0.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_ggH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.S0.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_ggH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.S0.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_ggH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.S0.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_ggH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.ggH.S0.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_ggH_S0.json"

#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.S0.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_bbH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.S0.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_bbH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.S0.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_bbH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.S0.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_bbH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.S0.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_bbH_S0.json"
#combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombine.bbH.S0.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_bbH_S0.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.ggH.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_bbbscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.ggH.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_bbbscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.ggH.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_bbbscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.ggH.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_bbbscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.ggH.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_bbbscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.ggH.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_bbbscale_ggH.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.bbH.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_bbbscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.bbH.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_bbbscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.bbH.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_bbbscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.bbH.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_bbbscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.bbH.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_bbbscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombinebbbscale.bbH.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_bbbscale_bbH.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.ggH.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_allscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.ggH.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_allscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.ggH.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_allscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.ggH.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_allscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.ggH.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_allscale_ggH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.ggH.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_allscale_ggH.json"

combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.bbH.lumi1.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi1_allscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.bbH.lumi10.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi10_allscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.bbH.lumi50.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi50_allscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.bbH.lumi100.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi100_allscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.bbH.lumi300.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi300_allscale_bbH.json"
combineTool.py -M CollectLimits output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/higgsCombineallscale.bbH.lumi3000.* --use-dirs -o "mssm_projection_ECFA_shapes_rebin0p8_shiftcen_lumi3000_allscale_bbH.json"
