#combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doInitialFit --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=1,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi1" --setPhysicsModelParameterRanges r_ggH=-3,3:r_bbH=-3,3  --freezeNuisances lumiscale
#combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doInitialFit --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=21.7391304348,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi50" --setPhysicsModelParameterRanges r_ggH=-3,3:r_bbH=-3,3  --freezeNuisances lumiscale
#combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doInitialFit --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=43.4782608696,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi100" --setPhysicsModelParameterRanges r_ggH=-2,2:r_bbH=-2,2  --freezeNuisances lumiscale
#combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doInitialFit --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=130.434782609,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi300" --setPhysicsModelParameterRanges r_ggH=-1,1:r_bbH=-1,1  --freezeNuisances lumiscale
#combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doInitialFit --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=1304.34782609,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi3000" --setPhysicsModelParameterRanges r_ggH=-1,1:r_bbH=-1,1  --freezeNuisances lumiscale



combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doFits --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=1,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi1" --setPhysicsModelParameterRanges r_ggH=-3,3:r_bbH=-3,3  --freezeNuisances lumiscale  --job-mode 'lxbatch' --task-name 'impacts-m350-lumi1' --sub-opts '-q 1nh' --merge=2 
combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doFits --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=21.7391304348,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi50" --setPhysicsModelParameterRanges r_ggH=-3,3:r_bbH=-3,3  --freezeNuisances lumiscale  --job-mode 'lxbatch' --task-name 'impacts-m350-lumi50' --sub-opts '-q 1nh' --merge=2
combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doFits --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=43.4782608696,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi100" --setPhysicsModelParameterRanges r_ggH=-2,2:r_bbH=-2,2  --freezeNuisances lumiscale  --job-mode 'lxbatch' --task-name 'impacts-m350-lumi100' --sub-opts '-q 1nh' 
combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doFits --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=130.434782609,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi300" --setPhysicsModelParameterRanges r_ggH=-1,1:r_bbH=-1,1  --freezeNuisances lumiscale  --job-mode 'lxbatch' --task-name 'impacts-m350-lumi300' --sub-opts '-q 1nh' 
combineTool.py -M Impacts -d output/mssm_projection_ECFA_shapes_rebin0p8_shiftcen/cmb/ws.root -m 350 --doFits --robustFit 1 -t -1 --setPhysicsModelParameters lumiscale=1304.34782609,r_ggH=0.3,r_bbH=0.3 -n ".350.lumi3000" --setPhysicsModelParameterRanges r_ggH=-1,1:r_bbH=-1,1  --freezeNuisances lumiscale  --job-mode 'lxbatch' --task-name 'impacts-m350-lumi3000' --sub-opts '-q 1nh' 


